### ISSUE TITLE
Yo bro some suggestion

### ISSUE THREAD

**Issue by furax124** [TheCuteOwl/Dualhooker#1]
Don't leave it as txt the output compile it as exe use nuikta it's better than pyinstaller because it's not an archive otherwise it's not a bad repo but python is poo you should do it in another language

Traduit avec DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation

**Comment by furax124** [comment]
Its fucking ugly do it more smarter

**Comment by TheCuteOwl** [comment]
It would be dumb

The objective is to make a Dualhook with 0 detection which is hidden with the “;” technique.

**Comment by furax124** [comment]
> It would be dumb
> 
> 
> 
> The objective is to make a Dualhook with 0 detection which is hidden with the “;” technique.

Yeah but compile it this code is ugly it's like a assembly of shit

**Comment by TheCuteOwl** [comment]
i only wanted to make it undetectable i don't really care

**Comment by furax124** [comment]
> > > It would be dumb
> 
> > > The objective is to make a Dualhook with 0 detection which is hidden with the “;” technique.
> 
> > 
> 
> > Yeah but compile it this code is ugly it's like a assembly of shit
> 
> 
> 
> And this code is make to be hidden in another "legit program"

Do it more smarter 
The code is very but very ugly my eyes and python 💩

**Comment by TheCuteOwl** [comment]
WHAT IS THE PROBLEM WITH PYTHON bruh

personally it's an good language where you can do everything easily and btw, you can't say ugly code when your only repo use js

**Comment by furax124** [comment]
> WHAT IS THE PROBLEM WITH PYTHON bruh
> 
> 
> 
> personally it's an good language where you can do everything easily and btw, you can't say ugly code when your only repo use js

It's just a injection lmao of rdimo and it's slow and for protection of code it's fucking shitty

**Comment by TheCuteOwl** [comment]
ik, but in all case the code is not that bad, i could make it slower, but i dont want to, useless

**Comment by furax124** [comment]
> ik, but in all case the code is not that bad, i could make it slower, but i dont want to, useless

It's bad.

**Comment by TheCuteOwl** [comment]
and why

**Comment by furax124** [comment]
> and why

Cause 1 all stealer are skidded by python lmao 
And 2 python it's a fucking bad language and a bad protector code

**Comment by TheCuteOwl** [comment]
First of all, skidded stealer are not my falt, i just help making the dualhook

Second, it is pretty easy to use and could be make into exe, but my work is not to make a payload exe

**Comment by furax124** [comment]
> First of all, skidded stealer are not my falt, i just help making the dualhook
> 
> 
> 
> Second, it is pretty easy to use and could be make into exe, but my work is not to make a payload exe
> 
> 

I already told you make it more fucking smarter like a blind of exe or something or un shell code loader

**Comment by TheCuteOwl** [comment]
Like, it will not, because it is suppose to be hidden in a script

so like i just make the payload and then the guy make the whole script in exe

**Comment by furax124** [comment]
> Like, it will not, because it is suppose to be hidden in a script
> 
> 
> 
> so like i just make the payload and then the guy make the whole script in exe

FUCKING DUMBASS do a option 💀

**Comment by furax124** [comment]
> ITS USELESS

🤡 it's like 20 ligne of code lmao

**Comment by TheCuteOwl** [comment]
But it's useless asf, like its an payload and should not be in exe

**Comment by furax124** [comment]
> But it's useless asf, like its an payload and should not be in exe

DO A FUCKING OPTION LIKE choose 1 or 2 it's very difficult ?

**Comment by furax124** [comment]
> BUT USELESS

Fucking asshole

**Comment by TheCuteOwl** [comment]
Bruh, just tell me why would i do that

**Comment by furax124** [comment]
> Bruh, just tell me why would i do that

Add features 🤡 very a dumb guy

**Comment by TheCuteOwl** [comment]
WHICH, because exe is dumb

**Comment by furax124** [comment]
> WHICH, because exe is dumb

🤓🤣🤡💀🫥

**Comment by TheCuteOwl** [comment]
bruh
