### ISSUE TITLE
Where the logs are put into

### ISSUE THREAD

**Issue by olangalo** [TheCuteOwl/Dualhooker#2]
so u know when i type in my script into the script area i dont know where it makes it

**Comment by TheCuteOwl** [comment]
In output.txt

**Comment by olangalo** [comment]
i cant find the output.txt
like where is it when i load it it doesnt make one

**Comment by TheCuteOwl** [comment]
Have you installed requirements.txt?

**Comment by olangalo** [comment]
nah fam also u know how to make a grabber cause im a script kiddie and i fr know nothing

**Comment by olangalo** [comment]
cause i wanna make my own one thats legit but with a dualhooker
\

**Comment by TheCuteOwl** [comment]
1. Bruh, dualhooking is not good
2. I'm the type of girl that's search all over github for dualhook, so I will pretty fastly delete it
3. If you are a script kiddie, just stole the code, like celer stealer on your github account ;)

**Comment by olangalo** [comment]
i feel too bad to pull kids info i was in a call with one that was having problems and he was 10 and i just send him the real thing and tell him to inactive the grabber and del it and show him how to add the mc hacks to his mods

**Comment by TheCuteOwl** [comment]
In all case, before doing stuff like dualhooking, learn to use a tool okay ^^?

**Comment by olangalo** [comment]
how did u learn how to do coding and learn tools

**Comment by TheCuteOwl** [comment]
On the internet, and just wanted to make stuff, So i make them even if it is hard
